securityonion-bro-scripts: add cve-2020-0601 script Security-Onion-Solutions/security-onion#1709

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -54,8 +54,9 @@ case "$1" in
 	sed -i 's|SpoolDir = /opt/bro/spool|SpoolDir = /nsm/bro/spool|g' $ZEEKCTLCFG || echo "Error updating $ZEEKCTLCFG"
 	sed -i 's|LogDir = /opt/bro/logs|LogDir = /nsm/bro/logs|g' $ZEEKCTLCFG || echo "Error updating $ZEEKCTLCFG"
 
+	PREV="pre-3.0.1"
 	LOCALBRO="/opt/zeek/share/zeek/site/local.zeek"
-	LOCALBROPREV="/opt/bro/share/bro/site/local.bro.pre-3.0.1"
+	LOCALBROPREV="/opt/bro/share/bro/site/local.bro.$PREV"
 
 	# Load Security Onion scripts        
 	if ! grep "@load securityonion" $LOCALBRO >/dev/null; then
@@ -103,7 +104,7 @@ case "$1" in
 	
 	# Existing deployments need to move /opt/bro/share/bro/intel/ to /opt/zeek/share/zeek/intel/
 	BROINTEL="/opt/bro/share/bro/intel"
-	if [ -d $BROINTEL ] && [ ! -L $BROINTEL ]; then
+	if [ -d $BROINTEL ] && [ ! -L $BROINTEL ] && [ ! -d /opt/zeek/share/zeek ]; then
 		mkdir -p  /opt/zeek/share/zeek/ 	|| echo "Error creating /opt/zeek/share/zeek/"
 		mv $BROINTEL /opt/zeek/share/zeek/ 	|| echo "Error moving $BROINTEL"
 	fi
@@ -142,7 +143,7 @@ EOF
 
 	# Existing deployments need to move the contents of /opt/bro/share/bro/policy/ to /opt/zeek/share/zeek/policy/
 	BROPOLICY="/opt/bro/share/bro/policy"
-	if [ -d $BROPOLICY ] && [ ! -L $BROPOLICY ]; then
+	if [ -d $BROPOLICY ] && [ ! -L $BROPOLICY ] && [ ! -d /opt/zeek/share/zeek/policy ]; then
 		mkdir -p  /opt/zeek/share/zeek/policy 		|| echo "Error creating /opt/zeek/share/zeek/"
 		mv $BROPOLICY/* /opt/zeek/share/zeek/policy/ 	|| echo "Error moving $BROPOLICY"
 		mv $BROPOLICY $BROPOLICY.old			|| echo "Renaming $BROPOLICY"
@@ -184,6 +185,15 @@ EOF
         	echo "@load hassh" >> $LOCALBRO
 	fi
 	
+	# Load cve-2020-0601
+	if ! grep "load cve-2020-0601" $LOCALBRO >/dev/null; then
+        	echo >> $LOCALBRO
+        	echo "# cve-2020-0601" >> $LOCALBRO
+		echo "# This script can detect exploit attempts for CVE-2020-0601." >> $LOCALBRO
+		echo "# It performs a simple check to see if a known curve is used in a certificate - if this is not the case a notice is raised." >> $LOCALBRO
+        	echo "@load cve-2020-0601" >> $LOCALBRO
+	fi
+	
 	# Modern versions of Setup disable Bro's syslog.log in Production Mode
 	# so if syslog.log was disabled in the previous local.bro, then re-add that setting
 	if ! grep "load disable-syslog" $LOCALBRO >/dev/null; then
@@ -196,8 +206,8 @@ EOF
 	fi
 
 	# move previous local.bro to new directory
-	if [ -f $LOCALBROPREV ]; then
-		mv $LOCALBROPREV /opt/zeek/share/zeek/site/
+	if [ -f $LOCALBROPREV ] && [ ! -f /opt/zeek/share/zeek/site/local.bro.$PREV ]; then
+		mv $LOCALBROPREV /opt/zeek/share/zeek/site/ || echo "Error moving $LOCALBROPREV"
 	fi
 
 	# Update broctl.cfg for AF_PACKET
@@ -226,7 +236,7 @@ EOF
 
 	# move /opt/bro/share/bro/disable-syslog to /opt/zeek/share/zeek/disable-syslog
 	DISABLESYSLOGDIR=/opt/bro/share/bro/disable-syslog
-	if [ -d $DISABLESYSLOGDIR ] && [ ! -L $DISABLESYSLOGDIR ]; then
+	if [ -d $DISABLESYSLOGDIR ] && [ ! -L $DISABLESYSLOGDIR ] && [ ! -d /opt/zeek/share/zeek/disable-syslog ]; then
 		mkdir -p /opt/zeek/share/zeek/ || echo "Error creating /opt/zeek/share/zeek/"
 		mv /opt/bro/share/bro/disable-syslog /opt/zeek/share/zeek/ || echo "Error moving /opt/bro/share/bro/disable-syslog/"
 	fi
@@ -246,7 +256,7 @@ EOF
 	# if /opt/bro/share/bro still exists as a full directory, rename it
 	DIR="/opt/bro/share/bro"
 	if [ -d $DIR ] && [ ! -L $DIR ]; then
-		mv $DIR $DIR.pre-3.0.1
+		mv $DIR $DIR.$PREV || echo "Error moving $DIR"
 	fi
 
 	# Existing and new deployments need to ensure symlink is in place
