move policy from /opt/bro/share/bro/ to /opt/zeek/share/zeek/

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -25,16 +25,6 @@ case "$1" in
 		ln -s $TARGET $LINK || echo "Error linking $LINK."
 	fi
 
-	# Symlink /opt/bro/share/bro to /opt/bro/share/zeek
-	#LINK="/opt/bro/share/bro"
-	#TARGET="zeek"
-	#if [ -e $LINK ]; then 
-	#	echo "Verified that $LINK exists."
-	#else
-	#	echo "Linking $LINK to $TARGET"
-	#	ln -s $TARGET $LINK || echo "Error linking $LINK."
-	#fi
-
 	# Symlink /opt/bro/share/zeek/site/local.bro to /opt/bro/share/zeek/site/local.zeek
 	LINK="/opt/bro/share/zeek/site/local.bro"
 	TARGET="local.zeek"
@@ -59,19 +49,10 @@ case "$1" in
 		ln -s $TARGET $LINK || echo "Error linking $LINK."
 	fi
 
-	# Create symlinks for disable-syslog, intel, and sguild_bro
-	for i in disable-syslog intel sguild_bro; do
-		LINK="/opt/zeek/share/zeek/$i"
-		TARGET="/opt/zeek/share/bro/$i"
-		if [ -d $TARGET ]; then
-			if [ -L $LINK ]; then
-				echo "$LINK already exists."
-			else
-				echo "Linking $LINK to $TARGET."
-				ln -s $TARGET $LINK || echo "Error linking $LINK."
-			fi
-		fi
-	done
+        # move SpoolDir and LogDir to /nsm
+	ZEEKCTLCFG=/opt/bro/etc/zeekctl.cfg
+	sed -i 's|SpoolDir = /opt/bro/spool|SpoolDir = /nsm/bro/spool|g' $ZEEKCTLCFG || echo "Error updating $ZEEKCTLCFG"
+	sed -i 's|LogDir = /opt/bro/logs|LogDir = /nsm/bro/logs|g' $ZEEKCTLCFG || echo "Error updating $ZEEKCTLCFG"
 
 	LOCALBRO="/opt/zeek/share/zeek/site/local.zeek"
 	LOCALBROPREV="/opt/bro/share/bro/site/local.bro.pre-3.0.1"
@@ -116,23 +97,42 @@ case "$1" in
 	if ! grep "load intel" $LOCALBRO >/dev/null; then
         	echo >> $LOCALBRO
         	echo "# You can load your own intel into:" >> $LOCALBRO
-        	echo "# /opt/bro/share/bro/intel/" >> $LOCALBRO
+        	echo "# /opt/zeek/share/zeek/intel/" >> $LOCALBRO
         	echo "@load intel" >> $LOCALBRO
 	fi
 	
-	# If /opt/bro/share/bro/intel/ doesn't already exist, create it
-	INTEL="/opt/bro/share/bro/intel/"
+	# Existing deployments need to move /opt/bro/share/bro/intel/ to /opt/zeek/share/zeek/intel/
+	BROINTEL="/opt/bro/share/bro/intel"
+	if [ -d $BROINTEL ] && [ ! -L $BROINTEL ]; then
+		mkdir -p  /opt/zeek/share/zeek/ 	|| echo "Error creating /opt/zeek/share/zeek/"
+		mv $BROINTEL /opt/zeek/share/zeek/ 	|| echo "Error moving $BROINTEL"
+	fi
+
+	# If /opt/zeek/share/zeek/intel/ doesn't already exist, create it
+	INTEL="/opt/zeek/share/zeek/intel/"
 	mkdir -p $INTEL
 
-	# If __load__.bro doesn't already exist, create it with default values
-	INTEL_LOAD="$INTEL/__load__.bro"
+	# Existing and new deployments need to ensure symlink is in place
+	if [ ! -d $BROINTEL ]; then
+		ln -s $INTEL $BROINTEL || echo "Error creating $BROINTEL symlink"
+	fi
+
+	# Rename intel __load__.zeek if necessary
+	INTELLOAD="/opt/zeek/share/zeek/intel/__load__"
+	if [ -f $INTELLOAD.bro ]; then
+		mv $INTELLOAD.bro $INTELLOAD.zeek || echo "Error renaming $INTELLOAD.bro"
+	fi
+
+
+	# If __load__.zeek doesn't already exist, create it with default values
+	INTEL_LOAD="$INTEL/__load__.zeek"
 	[ -f $INTEL_LOAD ] || cat << EOF > $INTEL_LOAD
 @load frameworks/intel/seen
 @load frameworks/intel/do_notice
 @load frameworks/files/hash-all-files
 
 redef Intel::read_files += {
-	"/opt/bro/share/bro/intel/intel.dat"
+	"/opt/zeek/share/zeek/intel/intel.dat"
 };
 EOF
 
@@ -145,6 +145,22 @@ EOF
 #www.honeynet.org	Intel::DOMAIN	Test Domain	T
 #4285358dd748ef74cb8161108e11cb73	Intel::FILE_HASH	Test MD5	T
 EOF
+
+	# Existing deployments need to move /opt/bro/share/bro/policy/ to /opt/zeek/share/zeek/policy/
+	BROPOLICY="/opt/bro/share/bro/policy"
+	if [ -d $BROPOLICY ] && [ ! -L $BROPOLICY ]; then
+		mkdir -p  /opt/zeek/share/zeek/ 	|| echo "Error creating /opt/zeek/share/zeek/"
+		mv $BROPOLICY /opt/zeek/share/zeek/ 	|| echo "Error moving $BROPOLICY"
+	fi
+
+	# If /opt/zeek/share/zeek/policy/ doesn't already exist, create it
+	POLICY="/opt/zeek/share/zeek/policy/"
+	mkdir -p $POLICY
+
+	# Existing and new deployments need to ensure symlink is in place
+	if [ ! -d $BROPOLICY ]; then
+		ln -s $POLICY $BROPOLICY || echo "Error creating $BROPOLICY symlink"
+	fi
 
 	# Load shellshock
 	if ! grep "load shellshock" $LOCALBRO >/dev/null; then
@@ -213,14 +229,22 @@ EOF
 		sed -i 's|^\[bro\]$|[zeek]|g' $NODECFG || echo "Error updating $NODECFG."
 	fi
 
-	# update /opt/bro/share/bro/disable-syslog/
-	DISABLESYSLOG="/opt/bro/share/bro/disable-syslog/disable-syslog"
+	# move /opt/bro/share/bro/disable-syslog to /opt/zeek/share/zeek/disable-syslog
+	DISABLESYSLOGDIR=/opt/bro/share/bro/disable-syslog
+	if [ -d $DISABLESYSLOGDIR ] && [ ! -L $DISABLESYSLOGDIR ]; then
+		mkdir -p /opt/zeek/share/zeek/ || echo "Error creating /opt/zeek/share/zeek/"
+		mv /opt/bro/share/bro/disable-syslog /opt/zeek/share/zeek/ || echo "Error moving /opt/bro/share/bro/disable-syslog/"
+	fi
+
+	# /opt/zeek/share/zeek/disable-syslog contains 2 scripts and they both need to be renamed and updated
+	DISABLESYSLOG="/opt/zeek/share/zeek/disable-syslog/disable-syslog"
 	if [ -f $DISABLESYSLOG.bro ]; then
-		sed -i 's|bro_init|zeek_init|g' $DISABLESYSLOG.bro || echo "Error update $DISABLESYSLOG.bro"
+		sed -i 's|bro_init|zeek_init|g' $DISABLESYSLOG.bro || echo "Error updating $DISABLESYSLOG.bro"
 		mv $DISABLESYSLOG.bro $DISABLESYSLOG.zeek || echo "Error renaming $DISABLESYSLOG.bro"
 	fi
-	DISABLESYSLOGLOCAL="/opt/bro/share/bro/disable-syslog/__load__"
+	DISABLESYSLOGLOCAL="/opt/zeek/share/zeek/disable-syslog/__load__"
 	if [ -f $DISABLESYSLOGLOCAL.bro ]; then
+		sed -i 's|disable-syslog.bro|disable-syslog|g' $DISABLESYSLOGLOCAL.bro || echo "Error updating $DISABLESYSLOGLOCAL.bro"
 		mv $DISABLESYSLOGLOCAL.bro $DISABLESYSLOGLOCAL.zeek || echo "Error renaming $DISABLESYSLOGLOCAL.bro"
 	fi
 
